name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: docker login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u wregen -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag wregen/mosquitto-exporter:$(git describe --tags --long) --tag wregen/mosquitto-exporter:latest
      - name: Docker Push
        run: docker push wregen/mosquitto-exporter:$(git describe --tags --long)
      - name: Docker Push
        run: docker push wregen/mosquitto-exporter:latest
